[package]
name = 'calculator_l05'
version = '1.0.0'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "testnet" }

[addresses]
metaschool = "0x1ee6cc7720969d835a8665400377c682232dfc86f711a9f48949f21074246189"
std = "0x1"
